---
abstract: 'Tiny URL builder'
author:
  - 'Tokuhiro Matsuno <tokuhirom@gmail.com>'
build_requires:
  Test::More: 0.98
  Tie::IxHash: 0
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.11.0, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: URI-Builder
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  URI::Builder:
    file: lib/URI/Builder.pm
    version: 0.01
requires:
  URL::Encode: 0
  perl: 5.008005
resources:
  bugtracker: https://github.com/tokuhirom/URI-Builder/issues
  homepage: https://github.com/tokuhirom/URI-Builder
  repository: git://github.com/tokuhirom/URI-Builder.git
version: 0.01
